import type { Filiere, Condition } from "@/types";

const CONDITIONS_COMMUNES: Condition[] = [
  {
    etape: 1,
    titre: "Présentation du dossier scolaire",
    description:
      "Analyse de vos bulletins et de votre profil académique par les établissements.",
  },
  {
    etape: 2,
    titre: "Test de langue (si dossier approuvé)",
    description:
      "Évaluation de votre niveau linguistique selon la formation choisie.",
  },
  {
    etape: 3,
    titre: "Validation du baccalauréat",
    description:
      "Fourniture du diplôme en fin d'année pour confirmer définitivement votre admission.",
  },
];

const filieres: Filiere[] = [
  // ─── KINÉSITHÉRAPIE ───────────────────────────────────────────────────
  {
    id: "kine",
    nom: "Kinésithérapie",
    couleur: "var(--color-filiere-kine)",
    nomBold: "Kinésithé",
    nomItalic: "rapie",
    tagline:
      "Former les kinés de demain dans les meilleures universités espagnoles — avec un diplôme reconnu dans toute l'Europe, sans concours d'entrée.",
    description:
      "Formation en kinésithérapie reconnue dans les meilleures universités espagnoles.",
    photo: "/images/filieres/kine.jpg",
    ctaLabel: "Candidater en Kinésithérapie",
    dureEtudesAnnees: 4,
    dureEtudesDetail: "240 crédits ECTS · Diplôme reconnu dans toute l'UE 🇪🇺",
    details: [
      { type: "diplome", label: "Diplôme reconnu dans toute l'Europe" },
      { type: "credits", value: 240 },
    ],
    stats: [
      { value: "4 ans", label: "de formation" },
      { value: "240", label: "crédits ECTS" },
      { value: "5", label: "villes" },
    ],
    sousTitre: "Le soin par le mouvement",
    introTitreBold: "Une formation complète, ",
    introTitreItalic: "sans concours",
    introDescription: `La filière de kinésithérapie en Espagne propose un enseignement de qualité au sein d'universités modernes équipées des dernières technologies. Accessible sur dossier, sans concours d'entrée, cette formation met l'accent sur la pratique dès le début du cursus. Les étudiants suivent des cours de thérapie manuelle dès la première année et débutent leurs stages en clinique dès la deuxième année, avec une immersion progressive dans le milieu professionnel. Ils évoluent dans un environnement bienveillant, centré sur la progression individuelle, et sont encadrés par des enseignants qualifiés, souvent en activité en clinique. La formation allie ainsi théorie, pratique et expérience terrain, avec plus de 1 200 heures de stages au cours du cursus.`,
    conditions: CONDITIONS_COMMUNES,
    debouches: [
      "Kinésithérapeute en cabinet libéral",
      "Kinésithérapeute du sport",
      "Kinésithérapeute hospitalier",
      "Rééducation cardio-respiratoire",
      "Kinésithérapie neurologique",
      "Kinésithérapie pédiatrique",
      "Rééducation uro-gynécologique & périnéale",
      "Rééducation fonctionnelle avancée",
      "Préparation physique & réathlétisation",
      "Enseignement et recherche",
    ],
    programme: [
      {
        phase: "Année 1-2",
        label: "Sciences fondamentales",
        matieres: [
          "Anatomie & biomécanique",
          "Physiologie humaine",
          "Neurologie",
          "Pathologies de l'appareil locomoteur",
          "Biophysique & électrophysiologie",
          "Psychologie du patient",
        ],
      },
      {
        phase: "Année 3-4",
        label: "Clinique & stages",
        matieres: [
          "Thérapies manuelles",
          "Électrothérapie & ultrasons",
          "Rééducation post-opératoire",
          "Kinésithérapie respiratoire",
          "Stages en centre de rééducation",
          "Mémoire de fin d'études (TFG)",
        ],
      },
    ],
    localisations: [
      {
        city: "Madrid",
        "ping-position-x": 49,
        "ping-position-y": 43,
        "mobile-ping-position-x": 49,
        "mobile-ping-position-y": 45,
        surnom: "La Villa y Corte",
        photo: "/images/localisations/madrid.jpeg",
      },
      {
        city: "Valence",
        "ping-position-x": 68,
        "ping-position-y": 52,
        "mobile-ping-position-x": 75,
        "mobile-ping-position-y": 52,
        surnom: "La Ciudad del Turia",
        photo: "/images/localisations/valence.jpeg",
      },
      {
        city: "Malaga",
        "ping-position-x": 45,
        "ping-position-y": 71,
        "mobile-ping-position-x": 43,
        "mobile-ping-position-y": 72,
        surnom: "La Costa del Sol",
        photo: "/images/localisations/malaga.jpeg",
      },
      {
        city: "Alicante",
        "ping-position-x": 59,
        "ping-position-y": 64,
        "mobile-ping-position-x": 63,
        "mobile-ping-position-y": 60,
        surnom: "La Ciudad de las Palomas",
        photo: "/images/localisations/alicante.jpeg",
      },
      {
        city: "Iles Canaries",
        "ping-position-x": 18,
        "ping-position-y": 92,
        "mobile-ping-position-x": 16,
        "mobile-ping-position-y": 90,
        surnom: "Las Islas del Sol",
        photo: "/images/localisations/iles_canaries.jpg",
      },
    ],
    cta: {
      description:
        "La kinésithérapie n'attend que vous. Des milliers d'étudiants français ont déjà fait le choix de l'Espagne. Et si c'était votre tour ?",
    },
  },

  // ─── DENTAIRE ─────────────────────────────────────────────────────────
  {
    id: "dentaire",
    nom: "Dentaire",
    couleur: "var(--color-filiere-dentaire)",
    nomBold: "Den",
    nomItalic: "taire",
    tagline:
      "Accédez aux facultés de médecine dentaire espagnoles sans PACES — un diplôme d'excellence reconnu dans toute l'Europe.",
    description:
      "Bénéficiez d'un enseignement d'excellence en médecine dentaire, reconnu en Europe.",
    photo: "/images/filieres/dentaire.jpg",
    ctaLabel: "Candidater en Dentaire",
    dureEtudesAnnees: 5,
    dureEtudesDetail: "300 crédits ECTS · Diplôme reconnu dans toute l'UE 🇪🇺",
    details: [
      { type: "diplome", label: "Diplôme reconnu dans toute l'Europe" },
      { type: "credits", value: 300 },
    ],
    stats: [
      { value: "5 ans", label: "de formation" },
      { value: "300", label: "crédits ECTS" },
      { value: "5", label: "villes" },
    ],
    sousTitre: "L'art du sourire, la science de la santé",
    introTitreBold: "Devenir dentiste, ",
    introTitreItalic: "sans passer par la PACES",
    introDescription: `La filière de médecine dentaire en Espagne offre un enseignement de qualité, dispensé au sein d'universités à la pointe de la technologie, disposant de cliniques dentaires modernes. Accessible sur dossier, sans concours d'entrée, elle permet un accès plus direct aux études. La formation intègre rapidement une dimension pratique, avec des travaux précliniques puis une prise en charge progressive de patients. Les étudiants évoluent dans un environnement d'apprentissage bienveillant, centré sur la progression individuelle, sans mise en compétition. Encadrés par des enseignants qualifiés, souvent docteurs et praticiens, ils développent des compétences solides, à la fois théoriques et cliniques.`,
    conditions: CONDITIONS_COMMUNES,
    debouches: [
      "Chirurgien-dentiste en cabinet (libéral)",
      "Dentiste en clinique ou centre de santé",
      "Exercice en milieu hospitalier",
      "Orthodontie (correction de l'alignement dentaire)",
      "Implantologie (pose d'implants dentaires)",
      "Chirurgie orale",
      "Dentisterie pédiatrique (soins chez l'enfant)",
      "Soins parodontaux et traitements spécialisés",
      "Recherche & enseignement",
    ],
    programme: [
      {
        phase: "Année 1-2",
        label: "Sciences fondamentales",
        matieres: [
          "Anatomie générale & dentaire",
          "Biologie cellulaire & biochimie",
          "Histologie & embryologie",
          "Physiologie humaine",
          "Microbiologie & immunologie",
          "Matériaux dentaires",
        ],
      },
      {
        phase: "Année 3-4",
        label: "Clinique",
        matieres: [
          "Dentisterie conservatrice",
          "Parodontologie",
          "Endodontie",
          "Prothèse fixe & amovible",
          "Orthodontie",
          "Pédodontie",
          "Radiologie & imagerie",
          "Premiers patients réels",
        ],
      },
      {
        phase: "Année 5",
        label: "Clinique avancée",
        matieres: [
          "Chirurgie buccale & implantologie",
          "Médecine buccale",
          "Stage en cabinet partenaire",
          "Mémoire de fin d'études (TFG)",
        ],
      },
    ],
    localisations: [
      {
        city: "Madrid",
        "ping-position-x": 49,
        "ping-position-y": 43,
        "mobile-ping-position-x": 49,
        "mobile-ping-position-y": 45,
        surnom: "La Villa y Corte",
        photo: "/images/localisations/madrid.jpeg",
      },
      {
        city: "Valence",
        "ping-position-x": 68,
        "ping-position-y": 52,
        "mobile-ping-position-x": 75,
        "mobile-ping-position-y": 52,
        surnom: "La Ciudad del Turia",
        photo: "/images/localisations/valence.jpeg",
      },
      {
        city: "Malaga",
        "ping-position-x": 45,
        "ping-position-y": 71,
        "mobile-ping-position-x": 43,
        "mobile-ping-position-y": 72,
        surnom: "La Costa del Sol",
        photo: "/images/localisations/malaga.jpeg",
      },
      {
        city: "Alicante",
        "ping-position-x": 59,
        "ping-position-y": 64,
        "mobile-ping-position-x": 63,
        "mobile-ping-position-y": 60,
        surnom: "La Ciudad de las Palomas",
        photo: "/images/localisations/alicante.jpeg",
      },
      {
        city: "Iles Canaries",
        "ping-position-x": 18,
        "ping-position-y": 92,
        "mobile-ping-position-x": 16,
        "mobile-ping-position-y": 90,
        surnom: "Las Islas del Sol",
        photo: "/images/localisations/iles_canaries.jpg",
      },
    ],
    cta: {
      description:
        "Le dentaire en Espagne, c'est un diplôme reconnu, une pratique clinique réelle et un avenir assuré. Et si vous commenciez dès maintenant ?",
    },
  },

  // ─── VÉTÉRINAIRE ──────────────────────────────────────────────────────
  {
    id: "veterinaire",
    nom: "Vétérinaire",
    couleur: "var(--color-filiere-veterinaire)",
    nomBold: "Vétéri",
    nomItalic: "naire",
    tagline:
      "Soigner les animaux est une vocation. Les universités espagnoles vous offrent une formation d'excellence pour en faire votre métier.",
    description:
      "Les écoles vétérinaires espagnoles sont parmi les meilleures d'Europe.",
    photo: "/images/filieres/veterinaire.jpg",
    ctaLabel: "Candidater en Vétérinaire",
    dureEtudesAnnees: 5,
    dureEtudesDetail: "300 crédits ECTS · Diplôme reconnu dans toute l'UE 🇪🇺",
    details: [
      { type: "diplome", label: "Diplôme reconnu dans toute l'Europe" },
      { type: "credits", value: 300 },
    ],
    stats: [
      { value: "5 ans", label: "de formation" },
      { value: "300", label: "crédits ECTS" },
      { value: "4", label: "villes" },
    ],
    sousTitre: "La passion au service du vivant",
    introTitreBold: "Devenir vétérinaire, ",
    introTitreItalic: "une vocation accessible",
    introDescription: `La filière vétérinaire en Espagne propose un enseignement de qualité au sein d'universités à la pointe de la technologie, disposant d'hôpitaux et de centres cliniques intégrés. Accessible sur dossier, sans concours d'entrée, cette formation accorde une place centrale à la pratique. Les étudiants sont amenés à manipuler et à intervenir dès les premières années, notamment au contact des animaux. Les stages cliniques se développent progressivement tout au long du cursus, permettant une immersion concrète dans le métier. Encadrés par des enseignants qualifiés et des professionnels en activité, les étudiants évoluent dans un environnement bienveillant, centré sur la progression individuelle.`,
    conditions: CONDITIONS_COMMUNES,
    debouches: [
      "Vétérinaire canin & félin — clinique généraliste ou spécialisée",
      "Vétérinaire équin — chevaux de sport, de course ou d'élevage",
      "Vétérinaire des animaux de rente — bovins, ovins, élevages agricoles",
      "Vétérinaire faune sauvage & zoo",
      "Vétérinaire chercheur — laboratoires, industrie pharmaceutique vétérinaire",
      "Vétérinaire urgentiste",
      "Spécialiste NAC — nouveaux animaux de compagnie (reptiles, oiseaux, rongeurs)",
      "Spécialiste en imagerie médicale",
      "Chirurgien vétérinaire",
    ],
    programme: [
      {
        phase: "Année 1-2",
        label: "Sciences fondamentales",
        matieres: [
          "Anatomie animale comparée",
          "Biologie & génétique",
          "Biochimie & physiologie",
          "Microbiologie & parasitologie",
          "Éthologie animale",
          "Zootechnie & productions animales",
        ],
      },
      {
        phase: "Année 3-4",
        label: "Clinique",
        matieres: [
          "Médecine interne (carnivores, équins, bovins)",
          "Chirurgie & anesthésie",
          "Pharmacologie & toxicologie",
          "Reproduction & obstétrique",
          "Pathologie infectieuse",
          "Imagerie médicale vétérinaire",
        ],
      },
      {
        phase: "Année 5",
        label: "Stages & spécialisation",
        matieres: [
          "Clinique hospitalière vétérinaire",
          "Santé publique & hygiène alimentaire",
          "Stage en structure partenaire",
          "Mémoire de fin d'études (TFG)",
        ],
      },
    ],
    localisations: [
      {
        city: "Madrid",
        "ping-position-x": 49,
        "ping-position-y": 43,
        "mobile-ping-position-x": 49,
        "mobile-ping-position-y": 45,
        surnom: "La Villa y Corte",
        photo: "/images/localisations/madrid.jpeg",
      },
      {
        city: "Valence",
        "ping-position-x": 68,
        "ping-position-y": 52,
        "mobile-ping-position-x": 75,
        "mobile-ping-position-y": 52,
        surnom: "La Ciudad del Turia",
        photo: "/images/localisations/valence.jpeg",
      },
      {
        city: "Malaga",
        "ping-position-x": 45,
        "ping-position-y": 71,
        "mobile-ping-position-x": 43,
        "mobile-ping-position-y": 72,
        surnom: "La Costa del Sol",
        photo: "/images/localisations/malaga.jpeg",
      },
      {
        city: "Alicante",
        "ping-position-x": 59,
        "ping-position-y": 64,
        "mobile-ping-position-x": 63,
        "mobile-ping-position-y": 60,
        surnom: "La Ciudad de las Palomas",
        photo: "/images/localisations/alicante.jpeg",
      },
      {
        city: "Iles Canaries",
        "ping-position-x": 18,
        "ping-position-y": 92,
        "mobile-ping-position-x": 16,
        "mobile-ping-position-y": 90,
        surnom: "Las Islas del Sol",
        photo: "/images/localisations/iles_canaries.jpg",
      },
    ],
    cta: {
      description:
        "Le vétérinaire est un métier de passion. En Espagne, cette passion devient accessible. Et si vous faisiez le premier pas ?",
    },
  },

  // ─── MÉDECINE ─────────────────────────────────────────────────────────
  {
    id: "infirmier",
    nom: "Médecine",
    couleur: "var(--color-filiere-infirmier)",
    nomBold: "Méde",
    nomItalic: "cine",
    tagline:
      "Intégrez les formations médicales espagnoles reconnues dans toute l'Europe — un parcours d'excellence accessible et concret.",
    description:
      "Formation médicale espagnole reconnue dans toute l'Union Européenne.",
    photo: "/images/filieres/medecine.jpeg",
    ctaLabel: "Candidater en Médecine",
    dureEtudesAnnees: 6,
    dureEtudesDetail: "360 crédits ECTS · Diplôme reconnu dans toute l'UE 🇪🇺",
    details: [
      { type: "diplome", label: "Diplôme reconnu dans toute l'Europe" },
      { type: "credits", value: 360 },
    ],
    stats: [
      { value: "6 ans", label: "de formation" },
      { value: "360", label: "crédits ECTS" },
      { value: "5", label: "villes" },
    ],
    sousTitre: "Au cœur du soin",
    introTitreBold: "Soigner, accompagner, ",
    introTitreItalic: "transformer des vies",
    introDescription: `La filière de médecine en Espagne propose un enseignement de qualité au sein d'universités à la pointe de la technologie, reconnues pour la qualité de leurs infrastructures. Accessible sur dossier, sans concours d'entrée, elle offre un accès plus direct aux études médicales. La formation se distingue par une intégration progressive de la pratique, avec des travaux dirigés, des simulations cliniques et des stages hospitaliers dès les premières années. Les étudiants évoluent dans un environnement bienveillant, centré sur la progression individuelle, et bénéficient d'un encadrement par des enseignants qualifiés et des professionnels de santé.`,
    conditions: CONDITIONS_COMMUNES,
    debouches: [
      "Médecin généraliste",
      "Médecin hospitalier",
      "Médecin urgentiste",
      "Médecin du sport",
      "Médecin en clinique privée",
      "Chirurgie (orthopédique, digestive...)",
      "Cardiologie",
      "Dermatologie",
      "Radiologie & imagerie médicale",
      "Anesthésie-réanimation",
    ],
    programme: [
      {
        phase: "Année 1-2",
        label: "Sciences & soins fondamentaux",
        matieres: [
          "Anatomie & physiologie",
          "Biologie & microbiologie",
          "Pharmacologie de base",
          "Soins infirmiers fondamentaux",
          "Éthique & déontologie",
          "Communication & relation d'aide",
        ],
      },
      {
        phase: "Année 3-4",
        label: "Clinique & stages",
        matieres: [
          "Soins en médecine & chirurgie",
          "Urgences & soins intensifs",
          "Pédiatrie & maternité",
          "Santé mentale & psychiatrie",
          "Gérontologie",
          "Stages hospitaliers (2 100 h minimum)",
        ],
      },
    ],
    localisations: [
      {
        city: "Madrid",
        "ping-position-x": 49,
        "ping-position-y": 43,
        "mobile-ping-position-x": 49,
        "mobile-ping-position-y": 45,
        surnom: "La Villa y Corte",
        photo: "/images/localisations/madrid.jpeg",
      },
      {
        city: "Valence",
        "ping-position-x": 68,
        "ping-position-y": 52,
        "mobile-ping-position-x": 75,
        "mobile-ping-position-y": 52,
        surnom: "La Ciudad del Turia",
        photo: "/images/localisations/valence.jpeg",
      },
      {
        city: "Malaga",
        "ping-position-x": 45,
        "ping-position-y": 71,
        "mobile-ping-position-x": 43,
        "mobile-ping-position-y": 72,
        surnom: "La Costa del Sol",
        photo: "/images/localisations/malaga.jpeg",
      },
      {
        city: "Alicante",
        "ping-position-x": 59,
        "ping-position-y": 64,
        "mobile-ping-position-x": 63,
        "mobile-ping-position-y": 60,
        surnom: "La Ciudad de las Palomas",
        photo: "/images/localisations/alicante.jpeg",
      },
      {
        city: "Iles Canaries",
        "ping-position-x": 18,
        "ping-position-y": 92,
        "mobile-ping-position-x": 16,
        "mobile-ping-position-y": 90,
        surnom: "Las Islas del Sol",
        photo: "/images/localisations/iles_canaries.jpg",
      },
    ],
    cta: {
      description:
        "Les métiers de la santé ont besoin de vous. En Espagne, la porte est ouverte. Et si vous faisiez le premier pas ?",
    },
  },
];

export default filieres;
